# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [1]:
import numpy as np
A = np.random.random((5,3))
B = np.random.random((3,2))
np.dot(A,B)

array([[0.28120887, 0.26606202],
       [0.1995165 , 0.27803447],
       [0.63502307, 0.64160352],
       [0.82444642, 0.86512684],
       [0.65207609, 0.63031397]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [7]:
import numpy as np
a = np.arange(10)
a[(a>3)&(a<8)] = a[(a>3)&(a<8)]*-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

legal: Z**Z, 2 << Z >> 2, 1j*Z, Z/1/1

illegal:

Z <- Z: <- 연산자는 존재하지 않음.

Z<Z>Z: Z < Z and Z > Z와 같이 표현해야 함.




#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. np.array(0) / np.array(0): 0으로 나누는 것은 불가능 하므로 NaN 생성
2. np.array(0) // np.array(0): 0으로 나누는 것은 불가능 하므로 NaN 생성
3. NaN의 형태는 변경할 수 었으므로 오류 발생

In [8]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-8-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-8-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-8-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [12]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common_value = np.intersect1d(Z1,Z2)
print('Z1:',Z1)
print('Z2:', Z2)
print(common_value)

Z1: [1 5 7 4 0 2 0 0 4 4]
Z2: [9 5 6 0 1 5 8 9 4 5]
[0 1 4 5]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [13]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-13-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

np.sqrt(-1)는 복소수를 다루지 않아 Nan이 나오는 반면 np.emath.sqrt(-1)는 복소수를 다루므로 false가 정답이다.

In [14]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [15]:
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [20]:
import numpy as np

A = np.array([1, 2, 3, 4], dtype=float)
B = np.array([4, 5, 6, 8], dtype=float)
np.add(A, B, out=A)
np.divide(-A, 2, out=A)
np.multiply(A, A, out=A)
print(A)

[ 6.25 12.25 20.25 36.  ]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [24]:
A = np.random.uniform(0,10,10)
print(A)
# 첫번째 방법
print(A - A%1)
# 두번째 방법
print(A // 1)

[5.01150233 7.72929763 0.54173895 0.47988044 2.74455389 6.89412867
 1.37019995 8.95791636 9.39097344 4.31958832]
[5. 7. 0. 0. 2. 6. 1. 8. 9. 4.]
[5. 7. 0. 0. 2. 6. 1. 8. 9. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [28]:
row_values = np.arange(5)
matrix = np.tile(row_values, (5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [29]:
a = np.random.random(10)
a.sort()
print(a)

[0.07505157 0.2547894  0.27431082 0.29783567 0.4374772  0.60210375
 0.79805083 0.8206617  0.8642327  0.90430162]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [31]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)
print(A,B)

[1 0 0 1 0] [0 1 1 1 1]


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [34]:
cartesian = np.random.rand(10, 2) * 10
print("cartesian:\n", cartesian)

x = cartesian[:, 0] #x좌표
y = cartesian[:, 1] #y좌표

r = np.sqrt(x**2 + y**2) #반지름r = sqrt(x^2 + y^2) 식 이용
theta = np.arctan2(y, x) #각도 계산

polar_coordinates = np.column_stack((r, theta))
print("\n극좌표 (r, θ):\n", polar_coordinates)

[0.81986635 0.83388617 0.76273843 0.83967159 1.2257235  1.24216482
 1.17263089 0.95159788 0.85479474 0.53272445]
[0.33913092 0.12350332 1.24383046 0.76082646 0.85461202 0.68804038
 0.93414058 0.48008342 1.04389045 0.52031169]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [32]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.51800445 0.15291519 0.42860831 0.73619835 0.         0.28923805
 0.09525604 0.80121227 0.64723356 0.72085337]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [36]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z)
print(v)

distances = np.abs(Z - v)
closest_index = np.argmin(distances)
closest_value = Z[closest_index]

print(closest_value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
80.25221715678074
80


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [41]:
import numpy as np
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [35]:
n = 5
p = 8
Z = np.zeros((n, n))

indices = np.random.choice(range(n * n), p, replace=False)
np.put(Z, indices, 1)

print(Z)

[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [38]:
# column 1
Z = np.random.randint(0,10,(3,3))
n = 1
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

1번째 열을 기준으로 정렬된 배열:
 [[0 7 8]
 [5 4 0]
 [9 1 7]]


In [39]:
# column 2
n = 2
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

2번째 열을 기준으로 정렬된 배열:
 [[9 1 7]
 [5 4 0]
 [0 7 8]]


In [40]:
# column 3
n = 3
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

3번째 열을 기준으로 정렬된 배열:
 [[5 4 0]
 [9 1 7]
 [0 7 8]]
