# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [11]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [12]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    vers

#### 3. Create a null vector of size 10 (★☆☆)

In [13]:
null_vector= np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [14]:
 print(null_vector.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [15]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
vector6 = np.arange(10,50)
print(vector6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
vector7 = np.sort(vector6)[::-1]
print(vector7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
matrix8 = np.arange(0,9)
matrix8 = matrix8.reshape(3,3)
print(matrix8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
array9 = np.array([1,2,0,0,4,0])
indices = array9[array9 != 0]
print(indices)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [20]:
help(np.identity)
identity_matrix=np.identity(3)
print(identity_matrix)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [21]:
array11 = np.random.random((3,3,3))
print(array11)

[[[0.1292658  0.61984851 0.59948938]
  [0.28075002 0.10096291 0.45709499]
  [0.89691424 0.59355178 0.3776336 ]]

 [[0.41497683 0.38315536 0.21056817]
  [0.95943803 0.46533638 0.26330603]
  [0.8999281  0.18701108 0.10855388]]

 [[0.36983534 0.50640434 0.19907238]
  [0.01215704 0.92615364 0.28566684]
  [0.13588707 0.53497037 0.59763077]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [22]:
array12 = np.random.random((10,10))
print(array12)
print('min value:\n', array12.min())
print('max value:\n', array12.max())

[[0.2528967  0.4991163  0.52789998 0.41470181 0.45963348 0.71586005
  0.72421579 0.22287275 0.2840817  0.96870642]
 [0.82743497 0.17368505 0.10112567 0.2705309  0.8900561  0.78104331
  0.05075932 0.78879075 0.85632627 0.77205302]
 [0.27241339 0.76843273 0.12839182 0.22833715 0.98485299 0.68767028
  0.49931389 0.02404881 0.57836726 0.28044158]
 [0.19968681 0.41297467 0.08381401 0.38163979 0.0978002  0.96133871
  0.27647033 0.17851286 0.85014152 0.18174794]
 [0.01291868 0.31518771 0.32505815 0.37757456 0.02406961 0.63491398
  0.09524155 0.1703242  0.851025   0.06361334]
 [0.40904827 0.99904645 0.00406    0.25276045 0.56497142 0.59311209
  0.63383463 0.62619719 0.8553359  0.28460428]
 [0.50170444 0.48566337 0.09881085 0.50409814 0.76114073 0.86024683
  0.73402105 0.67343453 0.89420362 0.46155951]
 [0.94563101 0.95495234 0.78531515 0.58391496 0.15797247 0.8960631
  0.33329606 0.84512397 0.63671116 0.18805216]
 [0.98185663 0.76883289 0.3909699  0.41241591 0.66652273 0.31553071
  0.94050014 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [23]:
array13 = np.random.random(30)
print(array13)
print('mean value:\n', array13.mean())

[0.87171263 0.8870456  0.09738879 0.59532011 0.98023563 0.08433656
 0.76630096 0.77345023 0.83775104 0.64900282 0.22444935 0.07350322
 0.05729594 0.23639936 0.56421868 0.11329515 0.65751333 0.27190647
 0.60537066 0.9903249  0.21071718 0.24900127 0.61502312 0.89363848
 0.40481019 0.08665875 0.84326339 0.74982645 0.95006258 0.10883849]
mean value:
 0.5149553764279579


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
array14 = np.zeros((5,5))
array14[0,:] = 1
array14[:,0] = 1
array14[4, :] = 1
array14[:,4] = 1
print(array14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan

False

False

nan

False

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [25]:
array16 = np.zeros((5,5))
array16[1,0] = 1
array16[2,1] = 2
array16[3,2] = 3
array16[4,3] = 4
print(array16)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [26]:
array17 = np.zeros((8,8))
array17[::2, ::2] = 1
array17[1::2, 1::2] = 1
print(array17)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [27]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [28]:
x = np.random.random((5,5))
print('random matrix:\n', x)
x_bar = x.mean()
s = x.std()
z = (x - x_bar)/s
print('normalized matrix:\n',z)

random matrix:
 [[0.7946567  0.04882196 0.1220032  0.49606076 0.08301364]
 [0.70094881 0.04816477 0.89718381 0.38557964 0.35820694]
 [0.69835891 0.41018079 0.80552576 0.26482347 0.01811513]
 [0.99954429 0.13568778 0.61742427 0.91299249 0.1726872 ]
 [0.74806753 0.19348756 0.30845382 0.52564425 0.21866092]]
normalized matrix:
 [[ 1.1683192  -1.27877414 -1.03866554  0.18862211 -1.16659078]
 [ 0.86086241 -1.2809304   1.50471194 -0.17386787 -0.26367807]
 [ 0.85236491 -0.0931512   1.2039807  -0.57007042 -1.37952363]
 [ 1.840558   -0.99376626  0.58681732  1.55658043 -0.87237069]
 [ 1.01545954 -0.80412446 -0.42691869  0.28568591 -0.72153034]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [29]:
RGBA = np.dtype([('red', np.ubyte), ('green', np.ubyte), ('blue', np.ubyte), ('alpha', np.ubyte)])
print(RGBA)

[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3